### ISSUE TITLE
Connectivity to HomeBrite A19 Household bulb does not work

### ISSUE THREAD

**Issue by truedat101** [nkaminski/csrmesh#4] opened 2016-07-04 00:54 UTC
I've got an A19 Household bulb, which is definitely running the CSRMesh stack (maybe 1.3?)

Steps:
- I turn it on
- discover via linux host: sudo hcitool lescan
- I obtain my mac: E0:34:E4:06:DD:A2 Feit Bulb
- I run the command as a regular user: csrmesh-cli --pin 0000 --dest E0:34:E4:06:DD:A2 --level 0
- the command executes two gatttool commands, and then nothing happens

Some platform details: Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I've attached the BLE Gatt information I gathered from an android app:

![screenshot_20160703-174734](https://cloud.githubusercontent.com/assets/64202/16548589/283dd78e-4147-11e6-9f74-974dfd2ffe02.png)

![screenshot_20160703-174730](https://cloud.githubusercontent.com/assets/64202/16548592/2dce08fe-4147-11e6-9dbb-3e38b74cd6a4.png)

![screenshot_20160703-174721](https://cloud.githubusercontent.com/assets/64202/16548593/327a4e1c-4147-11e6-9329-ba8324bed6c4.png)

**Comment by nkaminski** [comment] 2016-07-04 03:24
We have the same bulb so this should be easy to troubleshoot :)

Bulbs that are to be controlled using this need to be configured as part of a network. I only have a single bulb at the moment, so if possible, put one bulb on a separate network with a separate PIN.

Be aware that BTLE only supports ONE connection at a time and the Feit app remains connected to the bulbs for several minutes in the background after you close it, at least on Android. This was a frustrating issue that I had during development of this. 

Make sure you can connect to the bulb manually from the Linux computer using gatttool in interactive mode. i.e 

run: gatttool -b <bulb_mac> -I
and type "connect" at prompt

If you get errors such as "Socket error" or "Transport endpoint not connected", something else is connected to the bulb. Force stop the Feit app or temporarily turn off bluetooth on the phone running the app. I should really check the exit code of gatttool and report such errors on the console but I was a little too excited once I got the protocol implementation working and neglected to do so. Will add this in next release for sure.

You should then be able to use the csrmesh-cli utility as documented. Please let me know if you still have issues.

**Comment by truedat101** [comment] 2016-07-04 04:46
I can definitely connect via the gatttool.  No errors there.  Just nothing happening with the csrmesh tool.    Any other thoughts here on debugging the setup?

I have:
- iOS app setup a mesh network
- 2 bulbs

**Comment by truedat101** [comment] 2016-07-04 04:47
Since these aren't color lights, I don't pass the red green blue values.  That shouldn't matter, right?

Is there a particular version of gatttool needed?

**Comment by nkaminski** [comment] 2016-07-04 04:50
You should only need to pass --level for white bulbs, and you should not need a specific version of gatttool. Anything packaged with bluez 5.x or newer should work.

**Comment by nkaminski** [comment] 2016-07-04 04:51
Can you try with a single bulb network? I have not tested with more than one bulb in the network since I only have one bulb. There could be a "set destination" command that is needed with multi bulb networks.

**Comment by nkaminski** [comment] 2016-07-04 04:58
In terms of gatttool, I'm using 5.23-2+rpi2 on a Raspberry Pi 3. Any **bluez 5.x+** gatttool supports BTLE GATT and should work however.

**Comment by truedat101** [comment] 2016-07-04 05:13
Interesting.  So the app automatically groups the lightbulbs so that only a broadcast goes out to the group.  I noticed the on-off triggered both bulbs.  In any case, I could only detect a single bulb in the hcitool lescann.  Once I shut off the other bulb, can't see anything.  

Shut off the BLE on the iOS device, and I can see the one bulb.  Then I run:
csrmesh-cli --pin 0000 --dest E0:34:E4:06:DD:A2 --level 0

which executes the gatttool commands but no result or change.

**Comment by nkaminski** [comment] 2016-07-04 05:16
What bluez version are you using? Also, do you have an Android device such that we can use the Bluetooth HCI snoop logging to determine with certainty if this is a packet creation or communication issue?

**Comment by truedat101** [comment] 2016-07-04 05:19
Let me switch to my 'droid.

**Comment by nkaminski** [comment] 2016-07-04 05:22
Capture an on and off command using the bluetooth HCI snoop logging. What is written to handles 0x0011 and 0x0014?

**Comment by truedat101** [comment] 2016-07-04 05:26
Bluez version : 4.1.01.

Should I be building something newer?

**Comment by truedat101** [comment] 2016-07-04 05:27
What are the commands for the hci snoop logging that you use?

**Comment by truedat101** [comment] 2016-07-04 05:31
Ah, I see in the 'droid developer settings.

**Comment by nkaminski** [comment] 2016-07-04 05:32
Pre 5.0 bluez is known for unstable BTLE support. That could be the issue.
- Force stop Feit app
- Go into Settings > Developer Options > and tick "enable bluetooth HCI snoop logging". 
- Open feit app and switch on, wait several secs(makes it easier to ID packets), switch off.
- Untick snoop logging.
- Pull /sdcard/btsnoop_hci.log using adb
- open log in Wireshark

**Comment by nkaminski** [comment] 2016-07-04 05:34
Going to test on my Acer C720 too running arch linux and bluez 5.40.

**Comment by truedat101** [comment] 2016-07-04 05:36
Looks like that setting is missing from my Marshmellow 6.0 but it's still in the 5.x on my nexus.

**Comment by nkaminski** [comment] 2016-07-04 05:39
On the nexus, go to settings > about and tap on the kernel version 10 times ;)

**Comment by truedat101** [comment] 2016-07-04 05:40
Nexus is fine, it has the settings needed.  Marshmellow device is missing the HCI snoop logging.

**Comment by nkaminski** [comment] 2016-07-04 05:45
Reproduced issue on my C720, try changing char-write to char-write-req in gatt.py

**Comment by truedat101** [comment] 2016-07-04 05:51
Hmm, ok, the nexus5 isn't finding anything (no mesh found).  Trying this on an Nexus gen2 tablet.

**Comment by truedat101** [comment] 2016-07-04 05:56
Is there a trick to factory reset the bulbs?  None of my droids can find them after having paired with the iOS device.  Even the iOS device has problems.

**Comment by nkaminski** [comment] 2016-07-04 05:57
To reset: Turn the bulb on for 18 seconds then turn it back off for 1 second. Repeat the process 4 times.

**Comment by truedat101** [comment] 2016-07-04 06:05
Does it blink if it worked (reset)?  I'm having no luck with these android devices to connect.

**Comment by truedat101** [comment] 2016-07-04 06:05
In any case, should I just modify the source as you'd specified above?

**Comment by nkaminski** [comment] 2016-07-04 06:08
Yes, only works on my Pi with original source, both my Arch Linux chromebook and desktop PC require the change (and it still works on the Pi). The real app does a char-write-req as opposed to a char-write on closer inspection as well.

**Comment by truedat101** [comment] 2016-07-04 06:10
ur running ArchLinux on the pi?

**Comment by nkaminski** [comment] 2016-07-04 06:12
Raspbian jessie minimal on a Pi 3 and Arch Linux on an Acer C720 Chromebook. Changes pushed to repo too.

**Comment by truedat101** [comment] 2016-07-04 06:13
So weird, on the two nexus devices the BLE doesn't want to work with this HomeBrite app.  But fine on the Android 6.0 device.

**Comment by truedat101** [comment] 2016-07-04 06:13
Cool, I'll pull those changes.  If I can get this working on the desktop, will move to the router.

**Comment by nkaminski** [comment] 2016-07-04 06:13
The Android app is extremely buggy, part of the motivation for writing this ;)

**Comment by truedat101** [comment] 2016-07-04 06:14
Amen.  I don't completely understand the obsession with making apps the single point of failure and the reason your product gets returned to the store.

**Comment by nkaminski** [comment] 2016-07-04 06:15
Also when it failed earlier, did the gatttool commands take an unusually long time (>5 sec) to run? Running on my Acer C720, it would hang for close to a minute before continuing and the bulb not responding.

**Comment by truedat101** [comment] 2016-07-04 06:16
Actually, no, only if the ble endpoint had become unavailable.

**Comment by nkaminski** [comment] 2016-07-04 06:18
You should also get 2 lines of output stating "Characteristic value was written successfully" after making the change.

**Comment by truedat101** [comment] 2016-07-04 06:28
I patched the one gatt.py line.  I don't get a result other than the same as before.

**Comment by nkaminski** [comment] 2016-07-04 06:29
Does it print "Characteristic value was written successfully"?

**Comment by truedat101** [comment] 2016-07-04 06:29
I think I'm getting a cached bit of code here.  Did you push to pip?

**Comment by nkaminski** [comment] 2016-07-04 06:30
No, just github.

**Comment by nkaminski** [comment] 2016-07-04 06:32
Pushing to pypi now.

**Comment by truedat101** [comment] 2016-07-04 06:33
Sorry, I did a bad copy paste job.  Retrying.

**Comment by truedat101** [comment] 2016-07-04 06:35
Ok, so I can see it says the characteristics are written correctly.  However, no luck on change of state with the bulb.  Do I need a newer version of bluez?  I can build that and use the latest.

**Comment by nkaminski** [comment] 2016-07-04 06:35
Try a bluez version newer than 5.0. Both of my machines use bluez versions newer than 5.0.

**Comment by truedat101** [comment] 2016-07-04 06:36
Ok, I'll do that.

**Comment by truedat101** [comment] 2016-07-04 07:26
Building .... I have to remove my existing bluez package.  Not sure how this will work.

**Comment by truedat101** [comment] 2016-07-04 08:37
Hmm, that doesn't seem to help.I've got bluez 5.40 in there.  Thoughts?  I was hoping this was something I could bring up and verify easily, but seems like there are some nuances to deal with on each OS.

**Comment by nkaminski** [comment] 2016-07-04 09:02
Confirm the firmware version that your bulb runs, mine is on the latest version, 0.16

Also the fact that you get the characteristic write confirmation leads me to believe that the data is being sent properly.

There is a possiblity that there is a subtle difference in the key derivation algo between iOS and Android.

Try setting up one on Android again if possible. Hard reset the bulb and clear the android app's data before starting and you should be able to get it working. The Android app's bugs prevent it from being able to join an existing network successfully.

**Comment by truedat101** [comment] 2016-07-04 14:36
Not sure how I confirm that firmware version.

**Comment by truedat101** [comment] 2016-07-04 14:40
I've switched to Android, but I'll try to double check that my factory reset works.

**Comment by truedat101** [comment] 2016-07-04 14:57
Also, HomeBrite app version is 1.0.8.

Odd, I can't even get the app to connect to the bulb after trying the reset.  

BTW is there any confirmation the reset works (a series of blinks or anything obvious)?

**Comment by truedat101** [comment] 2016-07-04 14:59
Looks like even it says it can't cannot, after it gives up, DON'T reset the pin.  It then lets you into the menu, and you can control the bulb.  (Guess my reset didn't work).

**Comment by truedat101** [comment] 2016-07-04 14:59
I have to create an account to get into the firmware stuff

**Comment by truedat101** [comment] 2016-07-04 15:07
Confirmed bulb is 0.16 FW

**Comment by truedat101** [comment] 2016-07-04 18:01
Also, my USB dongle may be a factor.  Using a CSR 1101 based dongle, which you'd think would be working :p .  I believe it supports BLE 4.0.

**Comment by nkaminski** [comment] 2016-07-04 18:24
There is not an obvious reset confirmation, other than the fact that the bulb is completely unconfigured and you have to explicitly reassign it to the network. Before calling this a BT hardware issue, can you capture an on and off broadcast using the Android hci snoop logging so that we can ensure that the packets being provided to gattool by my implementation are byte-identical to what your app is sending?

**Comment by truedat101** [comment] 2016-07-04 18:25
I'll try that.  I have to figure out how to do that capture from Marshmellow (android 6.0) since they removed the menu checkbox.  My other droid's were not operational with the CSRMesh network.

**Comment by nkaminski** [comment] 2016-07-04 18:26
And you need to be fairly accurate with the timings for a reset.

**Comment by truedat101** [comment] 2016-07-04 18:26
Seems there is a way from the app to "reset" state of bulbs and app from within the app if you are logged in.

**Comment by truedat101** [comment] 2016-07-04 18:27
Yes, the same goes for the Zigbee Bulbs.  The Cree that I have is a super difficult one.

**Comment by nkaminski** [comment] 2016-07-04 18:31
If it was a BT hardware issue, I would not think you would get the write confirmation too. This may be a case where one of the values that appeared to be constant is instead specific to the bulb. Getting a packet capture would be interesting and prove/disprove this theory.

**Comment by truedat101** [comment] 2016-07-04 18:43
I may have to switch back to using a 4.x or 5.x android, as I think my Phone's OEM didn't opt to allow the BLE HCI capture (it's an option they can choose to expose or not).  So I'll assume that I should be able to get the capture going.  I'll report back hopefully by 2pm PST.  I have three phones that might work, though two were not working yesterday.

**Comment by nkaminski** [comment] 2016-07-04 18:56
OK cool, since the Android app can join the mesh (kind of) and control a bulb initially setup using iOS, a scenario that I have just reproduced myself, we can safely rule out a difference in the pin derivation algorithm. This is either a BT hardware issue or a flaw in my protocol where one of the 3 constants is not actually constant but unique to a particular bulb.

**Comment by truedat101** [comment] 2016-07-04 18:58
I have a question, where do the handles 0x0011 and 0x0014 come from?  What do they represent?  I couldn't find any reference to these handles in the anlysis that I posted using my Bluetooth Finder tool.

**Comment by truedat101** [comment] 2016-07-04 18:58
What Bluetooth dongle do you use?  Or what chipset does it have?

**Comment by nkaminski** [comment] 2016-07-04 21:12
My Acer C720 uses a QC/Atheros AR9462 and my Raspberry Pi 3 uses the
BCM2837's built in bluetooth. Characteristics can be referenced by
either a 16 bit handle or a 128 bit UUID. The handle I am referencing is
the 16 bit characteristic identifier.

**Comment by truedat101** [comment] 2016-07-04 21:45
I examined the details of the services exposed in my Android BLE scanner, but I didn't see any 0x0011 or 0x0014 , unless I overlooked it, associated with a characteristic.

**Comment by truedat101** [comment] 2016-07-04 21:45
I finally managed to get a bulb associated with a Nexus5 with droid 5.0.x.  I'll grab the logs.

**Comment by truedat101** [comment] 2016-07-04 21:54
Posted the btsnoop_hci.log here: https://1drv.ms/u/s!AuIL2jCvMCqRgYdRfORA_LakEjIB4w

If you need me to re-run this a bit more cleanly, I can.  However, I had much difficulty getting the app to ever join a mesh and see any devices.

**Comment by nkaminski** [comment] 2016-07-04 22:30
Will look at it in a few hours.

**Comment by nkaminski** [comment] 2016-07-05 01:50
What was the network pin for the network that these packets were sent to?

On July 4, 2016 4:54:26 PM CDT, "David J. Kordsmeier" notifications@github.com wrote:

> Posted the btsnoop_hci.log here:
> https://1drv.ms/u/s!AuIL2jCvMCqRgYdRfORA_LakEjIB4w
> 
> If you need me to re-run this a bit more cleanly, I can.  However, I
> had much difficulty getting the app to ever join a mesh and see any
> devices.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/nkaminski/csrmesh/issues/4#issuecomment-230357844

## 

Sent from my Android device with K-9 Mail.

**Comment by truedat101** [comment] 2016-07-05 01:52
I believe it was 2222

**Comment by nkaminski** [comment] 2016-07-05 07:50
Assuming the second to last command before the end of the capture is a breadcast "off" command (please confirm), it looks like a protocol level bug where a value that was always zero in my case is actually not.

Decrypted payloads:
My "broadcast off":            00007311000000000000
Yours from the packet cap:00007311**0180**00000000

Going to cleanup my decryption function and add that to the repo since that will ease debugging greatly. Will investigate more extensively tomorrow too since it is getting late.

**Comment by nkaminski** [comment] 2016-07-05 07:54
Last command in capture looks the same (confirm that this is a "broadcast on"):

My implementation: 000073110000e4ffffff
Yours from pcap:00007311**0180**e4ffffff

And just for ref. what is currently known about the structure is: <2 pad bytes><2 byte opcode><2 pad bytes?><1 byte white_level><1 byte red_level><1 byte green_level><1 byte blue_level>

**Comment by nkaminski** [comment] 2016-07-05 08:13
Created a branch called test that sends packets that exactly match yours, try testing with that and see if that resolves your issue. My bulb responds as expected to both 000073110000xxxxxxxx and 000073110180xxxxxxxx packets.

**Comment by truedat101** [comment] 2016-07-05 14:37
If it helps, I can re-run this with my session with a fixed set of steps:
- reset
- pair (2222)
- signal off
- signal on
- set level 50%

**Comment by truedat101** [comment] 2016-07-05 15:33
Log uploaded here: https://1drv.ms/u/s!AuIL2jCvMCqRgYdTvjiHpy429VoCmA

**Comment by truedat101** [comment] 2016-07-06 20:03
Let me know if there is anything else I can provide to help here.

**Comment by nkaminski** [comment] 2016-07-07 06:28
OK, will look into it more tomorrow. In the mean time, test my modified version in branch "test" and let me know if that works for you or not.

**Comment by truedat101** [comment] 2016-07-07 07:08
The test branch has just one change, correct: 8b246ed ?

I've patched in those changes, but no effect.

**Comment by nkaminski** [comment] 2016-07-07 13:18
Interesting, going to finish my packet decrypt function after work and school since it looks like there are more packets in your case than mine. Judging by the length, you have a packet other than an RTC set or lightlevel. Just want to confirm that  both the bulb and app have been reset / had their data cleared and that there are not any other bulbs other than this one that have been configured by the Android app since it was installed or reset?

**Comment by truedat101** [comment] 2016-07-07 14:21
I did exactly these steps.  

```
reset
pair (2222)
signal off
signal on
set level 50%
```

The reset was through the app.  I'm not 100% but it's possible the set level step doesn't ramp down but sends a series of levels.  It really depends on how smooth I was turning the level down.

I haven't gone and checked the file sizes, but was wondering if the snoop file is concatenated or truncated each time you enable HCI snooping.

**Comment by nkaminski** [comment] 2016-07-26 23:57
Have not lost sight of this, just very busy with work and school and should be able to spend some time on this shortly.

**Comment by truedat101** [comment] 2016-07-28 20:31
Ok, great, would love to get this working.  Let me know how I can help.

**Comment by nkaminski** [comment] 2016-08-01 07:53
Wrote a decryption and network key cracking routine to make it easier to examine large groups of packets to see what is different in your case to hopefully be able to explain this issue. However I had some difficulty making sense of the 2nd packet capture log. After further investigation, I discovered the cause of the issue was the key you used the 2nd time appears to be 1111 instead of 2222? Can you confirm?

> > > import csrmesh
> > > from binascii import hexlify, unhexlify
> > > d = unhexlify("d609d30080e84d2654293783e60fa182d3f06d0e7cb388ff")
> > > result = csrmesh.network_key_bruteforce(d)
> > > print(result[0])
> > > **1111**
> > > csrmesh.print_decrypted_packet(result[1])
> > > seq: 13830614
> > > magic: 80
> > > decpayload: 00007311018000000000
> > > encpayload: e84d2654293783e60fa1
> > > eof: ff
> > > hmac_packet: 82d3f06d0e7cb388
> > > hmac_computed: 82d3f06d0e7cb388

**Comment by truedat101** [comment] 2016-08-02 03:45
I'll reconfirm.  This was a while back, so I'll see what pin works.

**Comment by truedat101** [comment] 2016-08-08 15:42
Will have a look this week.  Been tied up as well with some stuff.

**Comment by nkaminski** [comment] 2016-08-13 18:16
Recently acquired a 2nd bulb and can confirm that issues DO occur if any bulb is "aware" of any other bulbs on its same network (i.e. with the same PIN) regardless of if they are powered or not. In such case, all commands sent to any of the bulbs on the mesh effect only the first bulb that was ever setup on such network. If the first bulb that was assigned to the network is unavailable or powered off, the command appears to send successfully but nothing happens. Hard resetting both bulbs **via power cycling** (resetting via the app does NOT work!) and setting each one up with a separate network PIN allows them to work as intended. I would like to look into this more myself and determine how to specify a destination other than the first device in packets.

**Comment by truedat101** [comment] 2016-08-14 04:34
Hmmm, this may explain my current problems, in addition to possibly having used the wrong pin.  A reset via the app maintained the old pin then.

**Comment by nkaminski** [comment] 2016-08-24 07:17
This looks like it has been resolved for the most part. Feel free to reopen this issue if you still have trouble.

**Closed as completed by nkaminski** 2016-08-24 07:17 UTC

**Comment by truedat101** [comment] 2016-12-18 01:47
I'll re-test this next week.  Working on some CES demo stuff, so would like to utilize this possibly since I need an alternative platform to Zigbee.
